version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal_network
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data

  gql:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - REDIS_CONNECTION_URL=redis://:${REDIS_PASSWORD}@cache:6379
      - NODE_ENV=production
    networks:
      - internal_network
    depends_on:
      - postgres
    volumes:
      - gql:/usr/src/app

volumes:
  gql:
  postgres-data:
  cache:
    driver: local

networks:
  internal_network:
    driver: bridge
